### ISSUE TITLE
userPermissions.filter error

### ISSUE THREAD

**Issue by light9** [BenZed/feathers-attribute-permissions#1]
BenZed, thanks for great job!

Can you please clarify, what do method:  `userPermissions.filter `?

When I use it in my users.hooks.js like `all:  [ userPermissions.filter ]` I receive those error:

``
error:  TypeError: [object Object] is not iterable!
    at module.exports.require.getIterator (/srv/node/test/node_modules/core-js/library/modules/core.get-iterator.js:5:42)
    at Object._callee$ (/srv/node/test/node_modules/feathers-attribute-permissions/lib/hooks/permissions-filter.js:70:53)
    at tryCatch (/srv/node/test/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/srv/node/test/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/srv/node/test/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/srv/node/test/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /srv/node/test/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise (<anonymous>)
    at F (/srv/node/test/node_modules/core-js/library/modules/_export.js:35:28)
    at Object.<anonymous> (/srv/node/test/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)``

My package.json:

`  "dependencies": {
    "body-parser": "^1.18.2",
    "compression": "^1.7.1",
    "cors": "^2.8.4",
    "feathers": "^2.2.3",
    "feathers-attribute-permissions": "^0.3.0",
    "feathers-authentication": "^1.3.0",
    "feathers-authentication-hooks": "^0.1.5",
    "feathers-authentication-jwt": "^0.3.2",
    "feathers-authentication-local": "^0.4.4",
    "feathers-configuration": "^0.4.2",
    "feathers-errors": "^2.9.2",
    "feathers-hooks": "^2.1.2",
    "feathers-hooks-common": "^3.10.0",
    "feathers-mongodb": "^2.9.1",
    "feathers-mongodb-fuzzy-search": "^1.1.0",
    "feathers-rest": "^1.8.1",
    "feathers-socketio": "^2.0.1",
    "helmet": "^3.9.0",
    "mongodb": "^2.2.33",
    "serve-favicon": "^2.4.5",
    "winston": "^2.3.1"
  },
  "devDependencies": {
    "eslint": "^4.8.0",
    "mocha": "^4.0.1",
    "request": "^2.83.0",
    "request-promise": "^4.2.2"
  }`

**Comment by BenZed** [comment]
Apologies for the delay!

The `filter` hook where the results get filtered from the database to what the user is actually allowed to see.

I think I know what's going on here; do you have pagination set up on the service this hook is using? It currently doesn't account for that. I'll fix that today.

If the service you're using this on *doesn't* have pagination, add this hook to your `after.all` hook config object:

`hook => console.log(hook.result)`

and paste what it says. Thanks!

**Comment by light9** [comment]
@BenZed thanks for reply. Yes, I have pagination and I cant loose it. I already tried to modify permissions-filter.js to something like this ` _iterator = (0, _getIterator3.default)(oldResult.data);`, but `newResult = [];` is constructed for array and I dont know how to get new object with standart pagination data like: `
{
data: [{...},{...}],
limit: 10,
skip: 0,
total: 2
}
`
 And my hooks after.all looks like that: 
`{
	total: 8,
	limit: 10,
	skip: 0,
	data: [{
			_id: 59 c79094c1c16968be4bee47,
			lastName: 'Black',
			firstName: 'Joe',
			description: 'test'
		},
		{
			_id: 59 c7d70858686f6e69a3fc80,
			lastName: 'Somebody',
			firstName: 'Somebody',
			description: 'test data'
		}
	]
}`
Thanks for your support!

**Comment by BenZed** [comment]
I'll fix this problem today.

**Comment by BenZed** [comment]
install `feathers-attribute-permissions@0.3.2` and your paginated services will work.

However, apon review, there are a couple of extra things that needed to be added to this repo:
- it currently does not support bulk queries when editing
- `$limit` query parameter (and perhaps some others) will return incorrect results.

I don't have the time to fix these today, but they will be fixed before this package reaches 1.0.0.

**Comment by light9** [comment]
@BenZed Thanks a lot!
